[package]
name = "external_convertor"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.20", features = ["derive"] }
regex = "1.11.1"
reqwest = { version = "0.12.9", features = ["blocking", "json"] }
serde_json = "1.0.132"
tracing = "0.1.40"
url = "2.5.3"
